version: '3.4'

volumes:
  datafiles:

services:
  database:
    image: mysql:8.0.22
    container_name: DB_mysql
    ports:
      - "3307:3306"
    volumes:
      - datafiles:/var/lib/mysql
      #- "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root0++
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: lima-books
  
  api:
    container_name: lima-books
    build: 
      context: '.'
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Prod
      - Server=DB_mysql
      - Port=3306
      - Database=lima-books
      - User=dev
      - Password=1234
      - SslMode=Preferred