name: Docker

on:
  workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/lima_books:${{github.run_number}}

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{secrets.DOCKERHUB_USERNAME}}
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.PASSWORD_DOCKER_HUB}}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:     
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile    
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/lima_books:${{github.run_number}}
      
